### ISSUE TITLE
Images under "Trusted by" are not discoverable

### ISSUE THREAD

**Issue by non-Jedi** [vector-im/vector.im#19]
I have no idea who "W3F" is, and most won't recognize the KDE logo. Those images should either link to websites for the respective organizations or at least have some hover text.

**Comment by nadonomy** [comment]
Hey @non-Jedi— this issue is being closed as this repo is for the vector.im site.

We're not quite ready to open source the new [about.riot.im](about.riot.im) site so the code and issues for that are tracked in a private repo currently. I've echoed your issue there. Thanks for reporting!
