### ISSUE TITLE
Riot.im website doesn't describe New Vector business model

### ISSUE THREAD

**Issue by non-Jedi** [vector-im/vector.im#22]
Personally, if I wasn't at least somewhat familiar with NV already, I'd find the "Pricing" link in the footer taking you to https://about.riot.im/free a little bit suspicious. It would be nice if there was some brief description of New Vector's business model (how y'all make money) on that page.

**Comment by nadonomy** [comment]
Closing as per https://github.com/vector-im/vector.im/issues/19#issuecomment-475282487.

Relatedly, we're launching an improved vector.im site imminently (https://github.com/vector-im/vector.im/pull/25), which should also help clarify this.
