### ISSUE TITLE
Low mozilla observatory score. (HSTS, CSP...)

### ISSUE THREAD

**Issue by 532910** [vector-im/vector.im#34]
https://observatory.mozilla.org/analyze/vector.im
Grade F

 Content Security Policy (CSP) header not implemented
 HTTP Strict Transport Security (HSTS) header not implemented
 X-Content-Type-Options header not implemented
 X-XSS-Protection header not implemented

**Comment by nadonomy** [comment]
Hey @532910— thanks for filing this issue.

We're now tracking the cause of these issues internally and will be fixing them as a matter of hygiene and general security.

We'll close this issue in due course as we fix it.

**Comment by ara4n** [comment]
now A+
