### ISSUE TITLE
Where did the riot-desktop app go? Link is dead.

### ISSUE THREAD

**Issue by ilu33** [vector-im/vector.im#39]
I can't find it neither on the homepage (link is dead) nor on github. A desktop client that can handle encryption is urgently needed, since browsers cause problems (of the "hasn't send keys" variety) again and again.

**Comment by turt2live** [comment]
Duplicate of https://github.com/vector-im/riot-web/issues/9453

See https://twitter.com/RiotChat/status/1117110823023984640 for details.
