### ISSUE TITLE
cannot find friends by username

### ISSUE THREAD

**Issue by wiggle-woman** [vector-im/vector.im#54]
i tried reinstalling and creating another account to add myself, but the problem persists.

friends cannot find me and i cannot find them, across all riot.im platforms (mobile, ios, web, desktop)

edit: i also cannot find myself with device id

**Comment by wiggle-woman** [comment]
hi, i managed solve the problem:

when you search for friend type 'usename:matrix.org' otherwise you cant find them
this :matrix.org makes all the difference i guess

question to developers: is this a feature with a purpose or just bug?

**Comment by turt2live** [comment]
Questions are best asked in [#riot-web:matrix.org](https://matrix.to/#/#riot-web:matrix.org). This repository is not monitored for feature requests.
