### ISSUE TITLE
Update bash script

### ISSUE THREAD

**Issue by nadonomy** [vector-im/vector.im#71]
To replace

```<script type="text/javascript">WebFont.load({  google: {    families: ["Open Sans:300,300italic,400,400italic,600,600italic,700,700italic,800,800italic","Comfortaa:300,regular,700"]  }});</script>```

with

`<script src="js/webfont.load.js" type="text/javascript"></script>`

& replace

`<script src="https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.4.1.min.220afd743d.js?site=5c77c2472f5ab14c779c0975" type="text/javascript" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>`

with

`<script src="/js/jquery-3.3.1.min.js" type="text/javascript"></script>`

Best to push changes on top of this PR/branch: https://github.com/vector-im/vector.im/pull/66

**Comment by nadonomy** [comment]
@t3chguy just made this issue to better track what's needed.

**Comment by t3chguy** [comment]
https://gitlab.matrix.org/new-vector/element/element.io/-/merge_requests/1/diffs?view=parallel
