### ISSUE TITLE
About identity and vector.im

### ISSUE THREAD

**Issue by AnonymousWebHacker** [vector-im/vector.im#76]
Hello, my riot-desktop, without the internet, gives me a configuration error, and with the internet only, lets me log in to matrix.org or another homeserver. 
Vector.im, would you help me fix that? identity or something?

**Comment by t3chguy** [comment]
Unrelated to this repo. The issue you want is https://github.com/vector-im/riot-web/issues/11655
You can get around it by specifying your own config.json as per the docs. https://github.com/vector-im/riot-desktop#user-specified-configjson
